src/Entity/StockMarketData.php
<?php

namespace App\Entity;

use App\Repository\StockMarketDataRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StockMarketDataRepository::class)
 */
class StockMarketData
{

    /**
     * @ORM\Id
     * @ORM\OneToOne(targetEntity=Stocks::class, inversedBy="data", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $articleId;

    /**
     * @ORM\Column(type="decimal", precision=8, scale=2, nullable=true)
     */
    private $stockValue;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $valuesHistory;

    /**
     * @ORM\Column(type="decimal", precision=9, scale=6, nullable=true)
     */
    private $variation;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=6, nullable=true)
     */
    private $demandCoefficient;

    public function getId(): ?int
    {
        return $this->getArticleId()->getId();
    }

    public function getArticleId(): ?Stocks
    {
        return $this->articleId;
    }

    public function setArticleId(Stocks $articleId): self
    {
        $this->articleId = $articleId;

        return $this;
    }

    public function getStockValue(): ?string
    {
        return $this->stockValue;
    }

    public function setStockValue(?string $stockValue): self
    {
        $this->stockValue = $stockValue;

        return $this;
    }

    public function getValuesHistory(): ?string
    {
        return $this->valuesHistory;
    }

    public function setValuesHistory(?string $valuesHistory): self
    {
        $this->valuesHistory = $valuesHistory;

        return $this;
    }

    public function getVariation(): ?string
    {
        return $this->variation;
    }

    public function setVariation(?string $variation): self
    {
        $this->variation = $variation;

        return $this;
    }

    public function getDemandCoefficient(): ?string
    {
        return $this->demandCoefficient;
    }

    public function setDemandCoefficient(?string $demandCoefficient): self
    {
        $this->demandCoefficient = $demandCoefficient;

        return $this;
    }
}

src/AppBundle/Controller/ManagementController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\SellsManagement;
use AppBundle\Entity\Treasury;
use AppBundle\Entity\Zreport;
use Exception;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\Printer;
use Swift_Image;
use Swift_Message;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ManagementController extends BasicController
{
    protected $escposPrinterIP, $escposPrinterPort;
    protected $mailingListAddress, $sendingAddress;

    public function __construct($escposPrinterIP, $escposPrinterPort, $mailingListAddress, $sendingAddress)
    {
        $this->escposPrinterIP = $escposPrinterIP;
        $this->escposPrinterPort = $escposPrinterPort;
        $this->mailingListAddress = $mailingListAddress;
        $this->sendingAddress = $sendingAddress;
    }

    /**
     * @Route("/management", name="manage-sells")
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function manageSells(Request $request){
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            throw $this->createAccessDeniedException();
        }

        $this->getModes();

        $em = $this->getDoctrine()->getManager();
        $repo_stocks = $this->getDoctrine()->getRepository('AppBundle:Stocks');
        $repo_typeStocks = $this->getDoctrine()->getRepository('AppBundle:TypeStocks');

        $typeDraft = $repo_typeStocks->returnType('Fût');
        $typeBottle = $repo_typeStocks->returnType('Bouteille');
        $typeArticle = $repo_typeStocks->returnType('Nourriture ou autre');

        $management = new SellsManagement();

        $drafts = $repo_stocks->findBy(['type' => $typeDraft]);
        $bottles = $repo_stocks->findBy(['type' => $typeBottle]);
        $articles = $repo_stocks->findBy(['type' => $typeArticle]);

        foreach ($drafts as $draft){
            $management->getDrafts()->add($draft);
        }
        foreach ($bottles as $bottle){
            $management->getBottles()->add($bottle);
        }
        foreach ($articles as $article){
            $management->getArticles()->add($article);
        }

        $form = $this->createForm('AppBundle\Form\SellsManagementType', $management);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            foreach ($drafts as $draft) {
                $em->persist($draft);
            }
            foreach ($bottles as $bottle) {
                $em->persist($bottle);
            }
            foreach ($articles as $article) {
                $em->persist($article);
            }
            $em->flush();

            $this->addFlash('info', 'La liste des articles en vente a bien été mise à jour.');

            return $this->redirectToRoute('purchase');
        }

        $this->data['form'] = $form->createView();

        return $this->render("management/index.html.twig", $this->data);
    }

    /**
     * @Route("/management/runs/processing", name="processing-run")
     * @param Request $request
     * @return string
     */
    public function registerRun(Request $request)
    {
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            throw $this->createAccessDeniedException();
        }

        $offline = $request->get('offline');

        $repo_z = $this->getDoctrine()->getRepository('AppBundle:Zreport');
        $lastZTimestamp = $repo_z->returnLastZTimestamp()['timestamp'];

        $repo_transactions = $this->getDoctrine()->getRepository('AppBundle:Transactions');

        try {
            if (!$offline) {
                // Trying to open the cash-drawer before doing anything
                try {
                    $connector = new NetworkPrintConnector($this->escposPrinterIP, $this->escposPrinterPort);
                    $printer = new Printer($connector);
                    try {
                        $printer->pulse();
                        $this->addFlash(
                            'info',
                            "L'ouverture de la caisse a été effectuée."
                        );
                    } finally {
                        $printer->close();
                    }
                } catch (Exception $e) {
                    $this->addFlash(
                        'error',
                        "Impossible de se connecter à la caisse : veuillez vérifier les branchements"
                    );
                    return $this->redirectToRoute('manage-sells');
                }
            }

            $date = date("d/m/Y");
            $time = date("H:i:s");
            $user = $this->getUser();
            $username = $user->getUsername();

            if (!empty($lastZTimestamp)) {
                $transactions = $repo_transactions->returnTransactionsSince($lastZTimestamp);
            } else {
                $transactions = $repo_transactions->findAll();
            }

            $zReport = new Zreport();

            // Total transactions
            $nbTransactions = count($transactions);

            // Types de transactions
            $commandes = [
                "cash" => array(),
                "account" => array(),
                "pumpkin" => array(),
                "card" => array()
            ];
            //$remboursements = array();
            $rechargements = array();

            // Totaux des commandes par méthode de paiement
            $totComCash = 0;
            $totComAccount = 0;
            $totComPumpkin = 0;
            $totComCard = 0;

            // Totaux des remboursements par méthode de paiement
            $totRembCash = 0;
            $totRembAccount = 0;
            // Nb écocups rendues par méthode de paiement
            $totEcoCash = 0;
            $totEcoAccount = 0;

            // Totaux des rechargements par méthode de paiement
            $totRechCash = 0;
            $totRechPumpkin = 0;
            $totRechCard = 0;

            // Nombre de remboursement par méthode de paiement
            $nbRembCash = 0;
            $nbRembAccount = 0;

            // Utilisateurs (staff) ayant effectués des transactions
            $users = array();

            // Transactions présentant une exception (peut apparaître plusieurs fois)
            $erreurs = array();

            foreach ($transactions as $transaction) {
                // Tri par type
                switch ($transaction->getType()) {
                    case 1:
                        switch ($transaction->getMethode()) {
                            case "cash":
                                $totComCash += $transaction->getMontant();
                                foreach ($transaction->getDetails() as $detail) {
                                    if (!isset($commandes["cash"][$detail->getArticle()->getNom()])) {
                                        $commandes["cash"][$detail->getArticle()->getNom()] = array();
                                        $commandes["cash"][$detail->getArticle()->getNom()]["qty"] = $detail->getQuantite();
                                        $commandes["cash"][$detail->getArticle()->getNom()]["price"] = $detail->getQuantite() * $detail->getArticle()->getPrixVente();
                                    } else {
                                        $commandes["cash"][$detail->getArticle()->getNom()]["qty"] += $detail->getQuantite();
                                        $commandes["cash"][$detail->getArticle()->getNom()]["price"] += $detail->getQuantite() * $detail->getArticle()->getPrixVente();
                                    }
                                }
                                break;
                            case "account":
                                $totComAccount += $transaction->getMontant();
                                foreach ($transaction->getDetails() as $detail) {
                                    if (!isset($commandes["account"][$detail->getArticle()->getNom()])) {
                                        $commandes["account"][$detail->getArticle()->getNom()] = array();
                                        $commandes["account"][$detail->getArticle()->getNom()]["qty"] = $detail->getQuantite();
                                        $commandes["account"][$detail->getArticle()->getNom()]["price"] = $detail->getQuantite() * $detail->getArticle()->getPrixVente();
                                    } else {
                                        $commandes["account"][$detail->getArticle()->getNom()]["qty"] += $detail->getQuantite();
                                        $commandes["account"][$detail->getArticle()->getNom()]["price"] += $detail->getQuantite() * $detail->getArticle()->getPrixVente();
                                    }
                                }
                                break;
                            case "pumpkin":
                                $totComPumpkin += $transaction->getMontant();
                                foreach ($transaction->getDetails() as $detail) {
                                    if (!isset($commandes["pumpkin"][$detail->getArticle()->getNom()])) {
                                        $commandes["pumpkin"][$detail->getArticle()->getNom()] = array();
                                        $commandes["pumpkin"][$detail->getArticle()->getNom()]["qty"] = $detail->getQuantite();
                                        $commandes["pumpkin"][$detail->getArticle()->getNom()]["price"] = $detail->getQuantite() * $detail->getArticle()->getPrixVente();
                                    } else {
                                        $commandes["pumpkin"][$detail->getArticle()->getNom()]["qty"] += $detail->getQuantite();

templates/management/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tenue du {{ zreport.timestamp|date('d/m/Y H:i:s') }}{% endblock %}

{% block stylesheet %}
    {{ parent() }}
    {{ encore_entry_link_tags('management_details') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('management_details') }}
{% endblock %}

{% block body %}
    <div class="alert alert-light">
        <h1 class="display-4">Tenue du {{ zreport.timestamp|date('d/m/Y H:i:s') }}</h1>
    </div>

    <h2>Bilan de la tenue</h2>
    <div class="table-responsive mb-2">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Validée par</th>
                <th>Ventes</th>
                <th>Rechargements</th>
                <th>Remboursements</th>
                <th>Total <small>(hors remb.)</small></th>
                <th>Contenu de la caisse</th>
                <th>Contenu du coffre</th>
                <th>Nombre de transactions</th>
                <th class="table-actions"></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">{{ zreport.id }}</th>
                <td>{{ zreport.staff.username }}</td>
                <td>{{ zreport.totalCommand }}€</td>
                <td>{{ zreport.totalRefill }}€</td>
                <td>{{ zreport.totalRefund }}€</td>
                <td>{{ zreport.total }}€</td>
                <td>{{ zreport.treasury.cashRegister }}€</td>
                <td>{{ zreport.treasury.safe }}€</td>
                <td>{{ zreport.transactions|length }}</td>
                <td class="table-actions">
                    <div class="d-flex">
                        <div class="input-group justify-content-around mx-auto">
                            <a class="btn btn-secondary mt-1"
                               href="{{ path('management_runs_treasury_edit', { 'id': zreport.treasury.id }) }}">
                                <i class="fas fa-edit"></i> Trésorerie</a>
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <h2>Transactions de la tenue</h2>
    <div class="table-responsive mb-3">
        <table id="table" class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Utilisateur</th>
                <th>Compte</th>
                <th>Montant</th>
                <th>Méthode</th>
                <th>Horodatage</th>
                <th class="table-action">Détails</th>
            </tr>
            </thead>

            <tbody>
            {% for transaction in zreport.transactions %}
                <tr>
                    <th>{{ transaction.id }}</th>
                    <td>{{ transaction.staff is not null ? transaction.staff.username : "Utilisateur supprimé" }}</td>
                    <td>{% if transaction.account != NULL %}
                            {{ transaction.account.pseudo }}
                        {% elseif transaction.method == "account" or transaction.type == 3 %}
                            Compte supprimé
                        {% else %}
                            ---
                        {% endif %}
                    </td>
                    <td>{{ transaction.type == 2 ? - transaction.amount : transaction.amount }}€</td>
                    <td>
                        {% if transaction.method == "account" %}
                            Compte
                        {% elseif transaction.method == "cash" %}
                            Liquide
                        {% elseif transaction.method == "pumpkin" %}
                            Pumpkin
                        {% elseif transaction.method == "card" %}
                            Carte Bleue
                        {% else %}
                            Non reconnue
                        {% endif %}
                    </td>
                    <td>{{ transaction.timestamp|date('H:i:s d/m/Y') }}</td>
                    <td class="table-action">
                        <div class="d-flex justify-content-center">
                            {% if transaction.type == 1 %}
                                <div class="btn-group dropleft">
                                    <button type="button" class="btn btn-secondary dropdown-toggle no-arrow"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-info-circle" aria-hidden="true"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <h6 class="dropdown-header">Articles achetés</h6>
                                        {% if transaction.details is not empty %}
                                            {% for detail in transaction.details %}
                                                <span class="dropdown-item">{{ detail.article.name }} : {{ detail.quantity }}</span>
                                            {% endfor %}
                                        {% else %}
                                            <span class="dropdown-item">Articles supprimés</span>
                                        {% endif %}
                                    </div>
                                </div>
                            {% elseif transaction.type == 2 %}
                                {% if transaction.details is not empty %}
                                    <div class="btn-group dropleft">
                                        <button type="button" class="btn btn-secondary dropdown-toggle no-arrow"
                                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-minus" aria-hidden="true"></i>
                                        </button>
                                        <div class="dropdown-menu">
                                            <h6 class="dropdown-header">Articles retournés</h6>
                                            {% for detail in transaction.details %}
                                                <span class="dropdown-item">{{ detail.article.name }} : {{ detail.quantity }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-secondary" data-toggle="tooltip"
                                                data-placement="left" title="Reboursement">
                                            <i class="fas fa-minus" aria-hidden="true"></i>
                                        </button>
                                    </div>
                                {% endif %}
                            {% elseif transaction.type == 3 %}
                                <div class="btn-group">
                                    <button type="button" class="btn btn-secondary" data-toggle="tooltip"
                                            data-placement="left" title="Rechargement">
                                        <i class="fas fa-gas-pump" aria-hidden="true"></i>
                                    </button>
                                </div>
                            {% else %}
                                <div class="btn-group">
                                    <button type="button" class="btn btn-danger" data-toggle="tooltip"
                                            data-placement="left" title="Type de transaction inconnue">
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    </button>
                                </div>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/management/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la clôture{% endblock %}

{% block body %}
    <div class="alert alert-light">
        <h1 class="display-4">Modifier clôture du bar</h1>
    </div>

    {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_rest(form) }}
    <button type="submit" class="btn btn-warning btn-lg btn-block">Modifier</button>
    {{ form_end(form) }}
{% endblock %}

templates/management/history.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historique des tenues{% endblock %}

{% block stylesheet %}
    {{ parent() }}
    {{ encore_entry_link_tags('management_history') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('management_history') }}
{% endblock %}

{% block body %}
    <div class="alert alert-light">
        <h1 class="display-4">Historique des tenues</h1>
    </div>

    <div class="table-responsive">
        <table id="table" class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Validée par</th>
                <th>Ventes</th>
                <th>Rechargements</th>
                <th>Remboursements</th>
                <th>Total <small>(hors remb.)</small></th>
                <th>Caisse</th>
                <th>Coffre</th>
                <th>Nb transactions</th>
                <th>Date de clôture</th>
                <th class="table-actions"></th>
            </tr>
            </thead>

            <tbody>
            {% for zreport in zreports %}
                <tr>
                    <th scope="row">{{ zreport.id }}</th>
                    <td>{{ zreport.staff.username }}</td>
                    <td>{{ zreport.totalCommand }}€</td>
                    <td>{{ zreport.totalRefill }}€</td>
                    <td>{{ zreport.totalRefund }}€</td>
                    <td>{{ zreport.total }}€</td>
                    <td>{{ zreport.treasury.cashRegister }}€</td>
                    <td>{{ zreport.treasury.safe }}€</td>
                    <td>{{ zreport.transactions|length }}</td>
                    <td>{{ zreport.timestamp|date('H:i:s d/m/Y') }}</td>
                    <td class="table-actions">
                        <div class="d-flex">
                            <div class="input-group justify-content-around mx-auto">
                                <a class="btn btn-secondary mt-1 {{ is_granted(expression('"ROLE_TRESO" in roles'))==true ? "" : "disabled" }}"
                                   href="{{ path('management_runs_treasury_edit', { 'id': zreport.treasury.id }) }}">
                                    <i class="fas fa-edit"></i> Trésorerie</a>
                                <a class="btn btn-success mt-1"
                                   href="{{ path('management_runs_show', {'id': zreport.id}) }}">
                                    <i class="fas fa-plus"></i> Détails</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/management/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des ventes{% endblock %}

{% block stylesheet %}
    {{ parent() }}
    {{ encore_entry_link_tags('management_index') }}
{% endblock %}

{% block body %}
    <div class="alert alert-light">
        <h1 class="display-4">Gestion des mises en vente</h1>
    </div>

    {{ form_start(form) }}
    <div class="alert alert-secondary h4 mt-3">
        <i class="fas fa-beer"></i> Pressions
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col">En vente</th>
                <th scope="col">Nom pression</th>
                <th scope="col">Prix de la pinte</th>
                <th scope="col">Fûts restants</th>
            </tr>
            </thead>
            <tbody>
            {% for draft in form.drafts %}
                <tr>
                    <th scope="row">
                        <div class="custom-control custom-checkbox">
                            {{ form_widget(draft.isForSale, {
                                'attr':{'class':'custom-control-input'},
                                'label_attr':{'class':'custom-control-label'}
                            }) }}
                        </div>
                    </th>
                    <td>
                        {{ form_widget(draft.name, {'attr': {'class': ""}}) }}
                    </td>
                    <td>
                        {{ form_widget(draft.sellingPrice, {'attr': {'class': ""}}) }}
                    </td>
                    <td>
                        {{ form_widget(draft.quantity, {'attr': {'class': ""}}) }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="alert alert-secondary h4 mt-3">
        <i class="fas fa-wine-bottle"></i> Bouteilles
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col">En vente</th>
                <th scope="col">Nom bouteille</th>
                <th scope="col">Prix de vente</th>
                <th scope="col">Bouteilles restantes</th>
            </tr>
            </thead>
            <tbody>
            {% for bottle in form.bottles %}
                <tr>
                    <th scope="row">
                        <div class="custom-control custom-checkbox">
                            {{ form_widget(bottle.isForSale, {
                                'attr':{'class':'custom-control-input'},
                                'label_attr':{'class':'custom-control-label'}
                            }) }}
                        </div>
                    </th>
                    <td>
                        {{ form_widget(bottle.name, {'attr': {'class': ""}}) }}
                    </td>
                    <td>
                        {{ form_widget(bottle.sellingPrice, {'attr': {'class': ""}}) }}
                    </td>
                    <td>
                        {{ form_widget(bottle.quantity, {'attr': {'class': ""}}) }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="alert alert-secondary h4 mt-3">
        <i class="fas fa-pizza-slice"></i> Nourriture et autres
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col">En vente</th>
                <th scope="col">Nom article</th>
                <th scope="col">Prix de vente</th>
                <th scope="col">Articles restants</th>
            </tr>
            </thead>
            <tbody>
            {% for article in form.articles %}
                <tr>
                    <th scope="row">
                        <div class="custom-control custom-checkbox">
                            {{ form_widget(article.isForSale, {
                                'attr':{'class':'custom-control-input'},
                                'label_attr':{'class':'custom-control-label'}
                            }) }}
                        </div>
                    </th>
                    <td>
                        {{ form_widget(article.name, {'attr': {'class': ""}}) }}
                    </td>
                    <td>
                        {{ form_widget(article.sellingPrice, {'attr': {'class': ""}}) }}
                    </td>
                    <td>
                        {{ form_widget(article.quantity, {'attr': {'class': ""}}) }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <button class="btn btn-success btn-lg btn-block" type="submit">
        Mettre à jour
    </button>
    {{ form_end(form) }}


    <div class="alert alert-light mt-3">
        <h1 class="display-4">Gestion des tenues</h1>
    </div>

    <a class="btn btn-success btn-lg btn-block" href="{{ path('management_runs_index') }}">Historique</a>
    <a class="btn btn-warning btn-lg btn-block" href="{{ path('management_runs_new') }}"
       onclick="return confirm('Cette action effectue le bilan des ventes depuis la dernière clôture et imprime le ticket Z.\nLe bar doit être entièrement fermé pour effectuer cette action !')"
       data-toggle="tooltip" title="Fait le bilan des ventes depuis la dernière clôture et imprime le ticket Z">
        Clore la tenue</a>
    <a class="btn btn-outline-warning btn-lg btn-block" href="{{ path('management_runs_new', {'offline': true}) }}"
       onclick="return confirm('Cette action effectue le bilan des ventes depuis la dernière clôture et envoie le ticket Z.\nLe bar doit être entièrement fermé pour effectuer cette action !')"
       data-toggle="tooltip" title="Fait le bilan des ventes depuis la dernière clôture et envoie le ticket Z">
        Clore la tenue (caisse offline)</a>
{% endblock %}

templates/management/treasury.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clôture du bar{% endblock %}

{% block body %}
    <div class="alert alert-light">
        <h1 class="display-4">Clôture du bar</h1>
    </div>

    {{ form_start(form) }}
    {{ form_errors(form) }}
    <div class="form-group">
        <label for="mvt-coffre" class="required">Mouvement dans le coffre <small>(négatif si du coffre vers la
                caisse)</small></label>
        <div class="input-group">
            <input id="mvt-coffre" name="mvt-coffre" required="required" class="form-control" type="text">
            <div class="input-group-append">
                <span class="input-group-text"> €</span>
            </div>
        </div>
    </div>
    {{ form_row(form.cashRegister) }}
    {{ form_rest(form) }}
    <button type="submit" class="btn btn-success btn-lg btn-block">Valider</button>
    {{ form_end(form) }}
{% endblock %}